/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package records.avro;
@org.apache.avro.specific.AvroGenerated
public enum RequestMethod implements org.apache.avro.generic.GenericEnumSymbol<RequestMethod> {
  GET, POST, HEAD, OPTIONS, PUT, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RequestMethod\",\"namespace\":\"records.avro\",\"symbols\":[\"GET\",\"POST\",\"HEAD\",\"OPTIONS\",\"PUT\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
